language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - if [[ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no

install:
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION h5py xarray pytables pytest-cov cython
  - if [[ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]]; then
        conda config --add channels diffpy;
        conda install --yes -n testenv diffpy.structure;
    fi
  - if [[ "${TRAVIS_PYTHON_VERSION}" == "3.5" ]]; then conda install --yes -n testenv flake8; fi
  - source activate testenv
  - pip install ase codecov periodictable
  - python setup.py build_ext --inplace

script:
  - py.test --cov=javelin --doctest-modules javelin tests
  - if [[ "${TRAVIS_PYTHON_VERSION}" == "3.5" ]]; then flake8; fi

after_success:
  - codecov
